# Run in a VS 2022 x64 developer PowerShell, with the Qt 6.8.3 MSVC kit.
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$QtRoot,
    [string]$DependenciesRoot = "$PSScriptRoot/../../build/windows-deps"
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
function Run([string]$Program, [string[]]$Arguments) {
    & $Program @Arguments
    if ($LASTEXITCODE -ne 0) { throw "$Program failed ($LASTEXITCODE)" }
}
$QtRoot = (Resolve-Path $QtRoot).Path
$DependenciesRoot = [IO.Path]::GetFullPath($DependenciesRoot)
$qmake = Join-Path $QtRoot 'bin/qmake.exe'
$version = & $qmake -query QT_VERSION
if ($LASTEXITCODE -ne 0 -or $version -ne '6.8.3') { throw 'Qt 6.8.3 is required.' }
if ($env:VSCMD_ARG_TGT_ARCH -ne 'x64') { throw 'Use a VS 2022 x64 developer shell.' }
Get-Command cl.exe, nmake.exe, cmake.exe -ErrorAction Stop | Out-Null
New-Item -ItemType Directory -Force "$DependenciesRoot/downloads", "$DependenciesRoot/sources" | Out-Null
$archives = @(
    @{ Name='qwt-6.3.0'; Directory='qwt-6.3.0'; Urls=@('https://downloads.sourceforge.net/project/qwt/qwt/6.3.0/qwt-6.3.0.zip', 'https://psychz.dl.sourceforge.net/project/qwt/qwt/6.3.0/qwt-6.3.0.zip', 'https://netix.dl.sourceforge.net/project/qwt/qwt/6.3.0/qwt-6.3.0.zip'); Hash='268d8d41974d263014fea13168324452f41e02880db573794f559995a4e11331' },
    @{ Name='googletest-1.17.0'; Directory='googletest-1.17.0'; Urls=@('https://codeload.github.com/google/googletest/zip/refs/tags/v1.17.0'); Hash='40d4ec942217dcc84a9ebe2a68584ada7d4a33a8ee958755763278ea1c5e18ff' }
)
foreach ($archive in $archives) {
    $zip = "$DependenciesRoot/downloads/$($archive.Name).zip"
    if (!(Test-Path $zip)) {
        $verified = $false
        foreach ($url in $archive.Urls) {
            # Some SourceForge redirects return an HTML landing page to HTTP
            # clients. Try official mirrors, accepting only the pinned bytes.
            & curl.exe --fail --location --retry 2 --connect-timeout 30 --max-time 300 --output "$zip.partial" $url
            if ($LASTEXITCODE -eq 0 -and (Get-FileHash "$zip.partial" -Algorithm SHA256).Hash -eq $archive.Hash) {
                $verified = $true
                break
            }
            Write-Warning "Archive unavailable or checksum mismatch at $url"
        }
        if (!$verified) { throw "Could not obtain checksum-verified $($archive.Name)." }
        Move-Item "$zip.partial" $zip -Force
    }
    if ((Get-FileHash $zip -Algorithm SHA256).Hash -ne $archive.Hash) { throw "Checksum mismatch: $zip; remove the corrupt archive and retry." }
    $source = "$DependenciesRoot/sources/$($archive.Directory)"
    $stamp = "$source/.openece-archive-sha256"
    if (!(Test-Path $stamp) -or (Get-Content $stamp -Raw).Trim() -ne $archive.Hash) {
        Expand-Archive $zip "$DependenciesRoot/sources" -Force
        Set-Content $stamp $archive.Hash
    }
}
# Reuse only builds from this script, compiler and Qt installation with intact outputs.
$fingerprint = "$( (Get-FileHash $PSCommandPath).Hash );$QtRoot;$version;$env:VCToolsVersion;$env:VSCMD_ARG_TGT_ARCH"
$stateFile = "$DependenciesRoot/bootstrap-state.json"
if (Test-Path $stateFile) {
    $state = Get-Content $stateFile -Raw | ConvertFrom-Json
    $intact = $state.Fingerprint -eq $fingerprint
    foreach ($file in $state.Files) {
        if (!(Test-Path $file.Path) -or (Get-FileHash $file.Path).Hash -ne $file.Hash) { $intact = $false; break }
    }
    if ($intact) { Write-Host 'Reusing verified Debug/Release dependencies.'; return }
}
$oldLocalPri = $env:QWT_LOCAL_PRI
try {
    $manifest = @('# Generated by the pinned OpenECE bootstrap; paths are relative to this file.')
    foreach ($config in @('Debug', 'Release')) {
        $build = "$DependenciesRoot/build/qwt-$config"
        $install = "$DependenciesRoot/qwt/lib/$config"
        New-Item -ItemType Directory -Force "$build/src", $install, "$DependenciesRoot/qwt/include" | Out-Null
        $localPri = "$build/openece.pri"
        @"
QWT_CONFIG -= QwtDesigner QwtDesignerSelfContained QwtExamples QwtPlayground QwtTests QwtSvg QwtOpenGL
CONFIG -= debug_and_release build_all debug release
CONFIG += $($config.ToLowerInvariant())
"@ | Set-Content $localPri
        $env:QWT_LOCAL_PRI = $localPri.Replace('\', '/')
        Push-Location "$build/src"
        try {
            Run $qmake @("$DependenciesRoot/sources/qwt-6.3.0/src/src.pro", '-spec', 'win32-msvc')
            Run 'nmake.exe' @('/NOLOGO')
        } finally { Pop-Location }
        $dlls = @(Get-ChildItem "$build/lib" -Filter '*.dll')
        if ($dlls.Count -ne 1) { throw "Expected one Qwt $config DLL in $build/lib." }
        $dll = $dlls[0]
        $lib = Join-Path $dll.DirectoryName ($dll.BaseName + '.lib')
        if (!(Test-Path $lib)) { throw "Missing import library $lib" }
        Copy-Item $dll.FullName, $lib $install -Force
        $upper = $config.ToUpperInvariant()
        $manifest += 'set(Qwt_RUNTIME_' + $upper + ' "${CMAKE_CURRENT_LIST_DIR}/lib/' + $config + '/' + $dll.Name + '")'
        $manifest += 'set(Qwt_LIBRARY_' + $upper + ' "${CMAKE_CURRENT_LIST_DIR}/lib/' + $config + '/' + [IO.Path]::GetFileName($lib) + '")'
    }
    Copy-Item "$DependenciesRoot/sources/qwt-6.3.0/src/*.h" "$DependenciesRoot/qwt/include" -Force
    $manifest | Set-Content "$DependenciesRoot/qwt/OpenECEQwtArtifacts.cmake"
} finally { $env:QWT_LOCAL_PRI = $oldLocalPri }
Run 'cmake.exe' @('-S', "$DependenciesRoot/sources/googletest-1.17.0", '-B', "$DependenciesRoot/build/gtest", '-G', 'Visual Studio 17 2022', '-A', 'x64', '-Dgtest_force_shared_crt=ON', '-DBUILD_GMOCK=OFF', '-DINSTALL_GTEST=ON', "-DCMAKE_INSTALL_PREFIX=$DependenciesRoot/gtest")
foreach ($config in @('Debug', 'Release')) {
    Run 'cmake.exe' @('--build', "$DependenciesRoot/build/gtest", '--config', $config, '--parallel', '4')
    Run 'cmake.exe' @('--install', "$DependenciesRoot/build/gtest", '--config', $config)
}
$files = @(Get-ChildItem "$DependenciesRoot/qwt", "$DependenciesRoot/gtest" -File -Recurse | ForEach-Object {
    @{ Path=$_.FullName; Hash=(Get-FileHash $_.FullName).Hash }
})
@{ Fingerprint=$fingerprint; Files=$files } | ConvertTo-Json -Depth 4 | Set-Content $stateFile
Write-Host "Dependencies installed in $DependenciesRoot"
