#!/usr/bin/env python3
"""Regenerate the checked-in Qt notices from the verified upstream source archive.

Usage: python scripts/windows/generate-qt-notices.py path/to/qtbase-6.8.3.tar.xz
No network access or third-party Python packages are used.
"""
import hashlib
import json
from pathlib import Path, PurePosixPath
import posixpath
import sys
import tarfile

SHA256 = "56001b905601bb9023d399f3ba780d7fa940f3e4861e496a7c490331f49e0b80"
SOURCE = "https://download.qt.io/official_releases/qt/6.8/6.8.3/submodules/qtbase-everywhere-src-6.8.3.tar.xz"
OUTPUT = Path(__file__).resolve().parents[2] / "packaging/Qt-6.8.3-NOTICES.txt"


def main():
    archive = Path(sys.argv[1])
    if hashlib.sha256(archive.read_bytes()).hexdigest() != SHA256:
        raise SystemExit("Qt source archive SHA-256 mismatch")
    # Read the compressed archive once; do not extract paths onto the filesystem.
    with tarfile.open(archive, mode="r|xz") as source:
        files = {
            member.name: source.extractfile(member).read()
            for member in source
            if member.isfile()
            and ("/LICENSES/" in member.name or "/3rdparty/" in member.name
                 or member.name.endswith("/qt_attribution.json")
                 or "license" in PurePosixPath(member.name).name.lower())
        }
    selected = {
        name for name in files
        if "/LICENSES/" in name
        or ("/3rdparty/" in name and PurePosixPath(name).name.lower().startswith(
            ("license", "licence", "copying", "notice", "copyright", "readme", "authors", "ftl.txt")))
        or name.endswith("/qt_attribution.json")
    }
    for name, content in files.items():
        if not name.endswith("/qt_attribution.json"):
            continue
        # Qt metadata permits literal newlines within JSON copyright strings.
        entries = json.loads(content, strict=False)
        for entry in entries if isinstance(entries, list) else [entries]:
            if "LicenseFile" in entry:
                license_path = posixpath.normpath(str(PurePosixPath(name).parent / entry["LicenseFile"]))
                if license_path not in files:
                    raise SystemExit(f"Missing referenced license: {license_path}")
                selected.add(license_path)
    parts = [
        "Qt Base 6.8.3 license texts and third-party attribution\n",
        f"Source: {SOURCE}\nSHA-256: {SHA256}\n",
        "Generated by scripts/windows/generate-qt-notices.py.\n"
        "Source-relative headings identify the original files; text is indented and whitespace normalized.\n"
        "This deliberately includes notices for source components not deployed by OpenECE.\n"
        "No Qt implementation sources are included.\n",
    ]
    for name in sorted(selected):
        try:
            content = files[name].decode("utf-8-sig")
        except UnicodeDecodeError:
            content = files[name].decode("iso-8859-1")
        parts.append(f"\n{'=' * 72}\n{name}\n{'=' * 72}\n\n")
        parts.append("\n".join(("    " + line.expandtabs(4)).rstrip() for line in content.splitlines()).rstrip() + "\n")
    OUTPUT.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"Wrote {len(selected)} upstream notice files to {OUTPUT} ({OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
