find_package(Eigen3 REQUIRED NO_MODULE)
if(Eigen3_VERSION VERSION_LESS 3.4)
    message(FATAL_ERROR "Eigen 3.4 or newer is required")
endif()
add_library(openece_circuits STATIC src/circuit.cpp src/mna.cpp src/dc.cpp src/ac_circuit.cpp)
add_library(OpenECE::circuits ALIAS openece_circuits)
target_include_directories(openece_circuits PUBLIC include)
target_compile_features(openece_circuits PUBLIC cxx_std_20)
target_link_libraries(openece_circuits PRIVATE openece_options)
target_link_libraries(openece_circuits PRIVATE Eigen3::Eigen)
target_compile_definitions(openece_circuits PRIVATE EIGEN_MPL2_ONLY)
